router:
  host: 192.168.14.1  # IP-адреса MikroTik RB951
  username: admin     # Логін
  password: ""        # Пароль
  port: 80            # Порт API (за замовчуванням 8728)

storage:
  output_path: data/{0}_{1}_{2}_bgp_data.json  # Шлях для збереження даних
  chart_path: data/{0}_{1}_line_chart.csv      #

running:
  interval: 1         # інтервал у секундах
  duration: 300.0     # час спостереження

charts:
  max_records: 30

analyze:
  minor-alert-level: 0.01
  major-alert-level: 0.3